<a href="https://colab.research.google.com/github/IvanOM-97/DPro-Exercises/blob/master/U24T1ImplementingMatrixMultiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
PROBLEMA 1 - ENTENDIENDO EL PRODUCTO DE MATRICES MEDIANTE CALCULO MANUAL
Para calcular el producto de matrices manualmente, siga estos pasos:
Este es un proceso importante para comprender mejor las operaciones con matrices.
- Combine cada fila de la matriz A y cada columna de la matriz B.
- Multiplique los elementos correspondientes para obtener la suma de todas las combinaciones.
- Mediante la multiplicación y la suma de cada elemento, se obtiene cada elemento de la matriz C.
'''

# Define matrices A and B manually
A = [[-1,  2,  3],
     [ 4, -5,  6],
     [ 7,  8, -9]]

B = [[ 0,  2,  1],
     [ 0,  2, -8],
     [ 2,  9, -1]]

# Initialize result matrix C with zeros
C = [[0 for _ in range(3)] for _ in range(3)]

# Matrix multiplication process (manual via loops)
for i in range(3):  # rows of A
    for j in range(3):  # columns of B
        total = 0
        for k in range(3):  # iterate through elements in the row/column
            total += A[i][k] * B[k][j]
        C[i][j] = total

# Print the resulting matrix
print("Matrix C = A * B:")
for row in C:
    print(row)

Matrix C = A * B:
[6, 29, -20]
[12, 52, 38]
[-18, -51, -48]


In [ ]:
'''
PROBLEMA 2 - CALCULANDO EL PRODUCTO DE MATRICES UTILZANDO NUMPY
'''

import numpy as np

# Define matrices a and b by numpy
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Calculate the product by MATMUL
result = np.matmul(a_ndarray, b_ndarray)
print("The product of a & b by method .matmul is:")
print(result)

# Calculate the product by DOT
result_dot = np.dot(a_ndarray, b_ndarray)
print("The product of a & b by method .dot is:")
print(result_dot)

# Other method to calculate the product
result_a = a_ndarray @ b_ndarray
print("The product of a & b is:")
print(result_a)

The product of a & b by method .matmul is:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
The product of a & b by method .dot is:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
The product of a & b is:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [ ]:
'''
PROBLEMA 3 - IMPLEMEMNTACION DESDE CERO DE PRODUCTOS MATRICIALES

'''
import numpy as np

# Matrix product process function
def matmul_scratch(a, b):
    result = np.zeros((a.shape[0], b.shape[1]))  # Create a zero matrix to store the results
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                result[i, j] += a[i, k] * b[k, j]
    return result

# Define matrices a and b by numpy
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Calculate the matrix product
scratch_result = matmul_scratch(a_ndarray, b_ndarray)

print(scratch_result)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [ ]:
'''
PROBLEMA 4 - QUE SUCEDE CUANDO UN CALCULO NO ESTA DEFINIDO?
'''
import numpy as np

# Define the matrix product test
def is_multiplicable(a, b):
    if a.shape[1] != b.shape[0]:
        print("Cannot compute matrix multiplication: number of columns does not match number of rows.")
        return False
    return True

# Define matrices a and b by numpy
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
b_ndarray = np.array([[0, 2, -8], [2, 9, -1]])

# Verify if the matrices are match
if is_multiplicable(a_ndarray, b_ndarray):
    print(np.matmul(a_ndarray, b_ndarray))

Cannot compute matrix multiplication: number of columns does not match number of rows.


In [ ]:
'''
PROBLEMA 5 - CALCULO DEL PRODUCTO DE MATRICES POR TRANSPOSICION
'''
import numpy as np

# Define matrices a and b by numpy
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
b_ndarray = np.array([[0, 2, -8], [2, 9, -1]])

# Transpose the matrix b
b_transposed = b_ndarray.T
result = np.matmul(a_ndarray, b_transposed)

print("The product of a & b by transpose is:")
print(result)


The product of a & b by transpose is:
[[-20  13]
 [-58 -43]]
